engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "**/**/*.js"
  - "**/**/*.css"
exclude_paths:
- "*.test.js"
- "test/"
- "coverage/"
- "dist/"
- "docs/"
- "docs-site/"
- "node_modules/"
- "build.js"
- "docs-bundle.js"
